### ISSUE TITLE
Set LUCKY_ENV to spec helper

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_cli#100]
Without this, it's pretty easy to erase your dev database when running tests. I thought it would be as simple as adding this to the top of the generated spec_helper.cr:

```crystal
ENV["LUCKY_ENV"] = "test"
```

but I don't see a generated spec_helper in the app skeleton.

**Comment by ianagne** [comment]
It looks like the spec_helper comes from `crystal init app`.  I created a PR to prepend the ENV to the spec_helper after its created to follow the pattern we're using with gitignore and shards.

**Comment by ianagne** [comment]
I'm super glad this got mentioned.  I'm realizing now that I've wiped my dev database more than once without noticing 😂

**Comment by paulcsmith** [comment]
Closed by #101
