### ISSUE TITLE
Allow using foreman, forego, heroku or node foreman in `lucky dev`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#102]
- [ ] Check which one is installed and use it in the `lucky dev` task. Use the first one that is installed.
- [ ] Update `bin/setup` to check for any of the possible options: Heroku CLI, foreman, forego or node foreman

Consider calling `lucky check_process_runners` in `bin/setup` which will raise if there are no runners installed. That way the logic can be in one place and not so spread out

**Comment by edwardloveall** [comment]
How would lucky choose which one to run? Should this be a config? CLI flag?

**Comment by paulcsmith** [comment]
@edwardloveall It would run `which heroku`, `which foreman` etc. and the first one that is installed would be used. Maybe in a followup feature you can add a .lucky file or something that specifics which one you'd like to use, but I'm not sure that'd be useful since all of those options do pretty much the same thing in the same way

**Comment by edwardloveall** [comment]
Right, that makes sense. Is there a specific order they should be chosen in? What if I have heroku and foreman installed?

**Comment by paulcsmith** [comment]
I’m not sure if it makes a difference so I think any order is fine. Maybe foreman, Heroku, forego and then Node foreman. They should all work the same so I think any order is ok. We can try it and change it up if it becomes an issue
