### ISSUE TITLE
Generating an action doesn't convert camelcase to snakecase

### ISSUE THREAD

**Issue by MattMSumner** [luckyframework/lucky_cli#110]
Running:

```cr
lucky gen.action HostedEvents::New
```

produces the following folder:

```
Done generating HostedEvents::New in ./src/actions/hostedevents
```

I would expect this to be snake cased.

**Comment by paulcsmith** [comment]
Thanks @MattMSumner! I opened this in https://github.com/luckyframework/lucky/issues/282 because that's where that generator is
