### ISSUE TITLE
Crystal 0.24 update

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky_cli#112]
This doesn't work on crystal 0.24 yet since there have been some breaking changes, including the relocation of `secure_random`

**Comment by paulcsmith** [comment]
Thanks for reporting this @watzon. Once 0.24 is officially released we'll release a new version of Lucky CLI and Lucky that will work with 0.24. I'll ping you and close this once that's done 👍 

For now I suggest using the latest released version which is 0.23.X (I don't remember the exact minor version)

**Comment by paulcsmith** [comment]
Closed by #127 

I still need to make a homebrew release and test the new versions of Lucky. So you may need to wait a day or two. It's close though!
