### ISSUE TITLE
When no tasks are present Runner can't determine the type of the tasks array

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_cli#116]
When running `lucky some.task` in a project that has no tasks, it throws an error:

>src/lucky_cli/runner.cr:10: can't infer block return type, try to cast the block body with `as`. See: https://github.com/crystal-lang/crystal/wiki/Compiler-error-messages#cant-infer-block-return-type
>
> `@@tasks.sort_by!(&.name)`

I'm a little surprised that this happens because at the top of the class, `@@tasks` has a type annotation:

```crystal
@@tasks = [] of LuckyCli::Task
```

**Comment by jwoertink** [comment]
I don't think this is an issue anymore. 

```
[14:54PM] junk (master)$ lucky some.task
Task some.task not found.
```

So I think it can be closed now.

**Comment by paulcsmith** [comment]
Thanks for looking into this!
