### ISSUE TITLE
Allow appending Task to task names

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#139]
This will help avoid conflicts with existing modules and tasks: e.g. `DevTask` instead of just `Dev`
 
So basically we strip “Task” from the end of the class name when inferring the Task name

**Comment by paulcsmith** [comment]
@edwardloveall this might be a good on to tackle if you’re interested. Here’s where the name isn’t generated: https://github.com/luckyframework/lucky_cli/blob/7c34d73dcccaaf4b2a950fb4d928f465086896f3/src/lucky_cli/task.cr#L6

For the spec you could tack on Task to one of the tasks in spec/support and the suite should still pass. LMK if you’re interested in tackling this.

**Comment by edwardloveall** [comment]
Yeah looks fun 😄 I'll take a look.

**Comment by edwardloveall** [comment]
Making sure I understand this correctly, appending `Task` is optional, but the last instance of `Task` is always stripped from the name. So `My::CoolTask` has the name of `my.cool` but also `My::Generator` has the name `my.generator`?

**Comment by paulcsmith** [comment]
Hmmm that is correct but it makes me wonder if this is a good idea. Might be too magic. Maybe just allowing s custom name is a better solution #138. What do you think?

**Comment by edwardloveall** [comment]
Yeah that seems like a good way to go.

**Comment by paulcsmith** [comment]
Closing this in favor of allowing custom task names
