### ISSUE TITLE
Running bin/setup throws an error about lucky_record

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_cli#143]
When I run the specs, the spec/integration/init_web_spec.cr throws the following error:

```
Error in tasks.cr:2: while requiring "./src/app"

require "./src/app"
^

in src/app.cr:1: while requiring "./dependencies"

require "./dependencies"
^

in src/dependencies.cr:1: while requiring "lucky_record": can't find file 'lucky_record' relative to '/path/to/crystal/lucky-src/cli/test-project/src'

require "lucky_record"
^
```

The test continues on and passes, but it seems odd that it would throw this compilation error.

**Comment by paulcsmith** [comment]
Hmm that’s strange. Try shards update to make sure everything is up to date. Also youll need crystal 0.24.1 (but I think you’re in that)

You may also need to add the —no-debut flag when running crystal spec. It’s a known issue that the crystal team is working in. Lmk if that works/helps
