### ISSUE TITLE
Trap ctrl-c in server.cr

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#163]
Thanks to @nicbet https://gitter.im/luckyframework/Lobby?at=5a67af946117191e61a380da

https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/src/server.cr should look like this near the end:

```crystal
puts "Listening on http://#{host}:#{port}"

Signal::INT.trap do
  server.close
end

server.listen
```

**Comment by Djok39** [comment]
bug still persist in master branch

**Comment by Djok39** [comment]
also, good idea to handle Signal::TERM too
