### ISSUE TITLE
Add a db.seed task

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#176]

**Comment by dtcristo** [comment]
Are you considering a `seeds.cr` in the same vein as `seeds.rb` from Rails?

In Rails I've been using the [seed migration](https://github.com/harrystech/seed_migration) gem that runs seeds incrementally, great for using seeds in production. A table in the DB keeps track of which seed migrations have already run in the same way as regular schema migrations. It gives much more power than a traditional `seeds.rb` file.

This gem rolls all the seeds up into `seeds.rb` just like schema migrations are dumped into `schema.rb`. However, I don't think this is necessary and feel it's best to just run all the seed migrations in order when deploying a new instance of the application.

Would you be open to a seed migration implementation as part of Lucky?

I would guess if this is were to be implemented it would fit best as part of lucky_migrator running seed scripts from `db/seed_migrations/*`.

It might have the following tasks:
```
lucky db.seed_migrate
lucky db.seed_rollback
lucky db.seed_rollback_all
```

And the following generator:
```
lucky gen.seed_migration AddWidgets
```

An example seed migration:
```crystal
class AddWidgets::V20171117153223 < LuckyMigrator::SeedMigration::V1
  def migrate
    # Add new widgets here
  end

  def rollback
    # Remove added widgets here
  end
end
```

Would you like a feature such as this to be part of the framework? If so I can look at implementing it myself and provide a PR.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky_cli/pull/187

**Comment by paulcsmith** [comment]
@dtcristo Thanks so much for the comment. I added 2 tasks for now: https://github.com/luckyframework/lucky_cli/commit/e0f51211521f087ad75df38384f6703d83b70b3f

I would definitely be open to some kind of tracked seeds like that, but it would have to be started as a separate package that is included in Lucky since I don't have much time to support it right now. 

If you'd like to take a shot at making a shard and using it in Lucky that'd be a great first start! I also wonder if you could run seeds inside regular migrations so that you don't need a separate "seed migrations" concept. I haven't tried that yet, but it may be worth exploring too!
