### ISSUE TITLE
Discussion: Make a web based wizard

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#220]
Instead of https://github.com/luckyframework/lucky_cli/issues/217

Instead of making a CLI wizard I think it might be better to have an online wizard that lets you pick and choose what you need, and has explanations for the options when you’re not sure what to do. 

At the end it would give you the command to use to generate your app. For example, the user might say they want an API only app without Auth. It would give them this command to run: “lucky init my-project —api —no-auth”

This is easier to implement, allows for better explanations of what the options are and teaches users how to use the CLI flags

**Comment by edwardloveall** [comment]
Interesting idea!

My first thought is that both a CLI and Web version of a wizard are a lot of work. Is there something you think a wizard will help with over our guides and and helpful CLI help text? Especially given the work it would take? Would those things get us started and then we can make a wizard if it's needed?

Perhaps I also find wizards very unhelpful. I like your idea that it generates a command, not an app to teach people about CLI args, but that won't scale. I.e. people won't/can't always look to wizards to teach them. At some point they'll have to reach for guides, errors, and docs.

P.S. I understand the actual work to build up a command from series of choices isn't that hard but there are other factors like setup, design (however minimal), and deployment that need to be done around a website. Those aren't present or already taken care of in the existing infrastructure.

**Comment by paulcsmith** [comment]
@edwardloveall Thanks for reeling me back into reality a bit :)

I think you're right that the easiest/simplest approach is having guides that outline the flags. That might be the best option for now. Then later on some kind of wizard/website/whatever could be added if necessary.

The reason I like the idea of a wizard is that you can be made aware of new options and I also kind of like visual interfaces and I know others do. This is by no means necessary though and time is probably better spent elsewhere. So I think this is a good plan:

* Add new CLI flags (--no-auth, --webpack=react,typescript, etc.)
* Document them in the relevant Lucky guide

Later on:

* Add the wizard/witch/warlock or whatever it is to give things a little extra spice.

Thoughts?

**Comment by paulcsmith** [comment]
Slight alteration. I might still include a wizard in the CLI since it's pretty much done :P We'll see though

**Comment by paulcsmith** [comment]
Here's what it looks like so far

<img width="751" alt="screen shot 2018-07-10 at 6 20 49 pm" src="https://user-images.githubusercontent.com/22394/42545651-06bfce20-846e-11e8-8ddd-b1859656f06c.png">

**Comment by sdzyba** [comment]
Personally I very much like CLI wizards with predefined answers.
For instance, I'm not that experienced with front end stack configuration, but `vue-cli` simplifies my life a lot when it comes to a new app generation:
<img width="505" alt="screen shot 2018-07-11 at 12 30 17" src="https://user-images.githubusercontent.com/5605160/42563323-a8d9df46-8506-11e8-82b4-ba1aadf289c7.png">

Same may be perfectly applied to Lucky I think.
Database selection (postgres, mysql, etc).
[Ameba](https://github.com/veelenga/ameba) inclusion (y/n).
CI config (travis, gitlab ci, etc).
Docker setup.
Project skeleton. `api/full` as @paulcsmith mentioned above or even an "advanced" mode where user can specify exact framework's components he wants like so:
<img width="321" alt="screen shot 2018-07-11 at 12 38 49" src="https://user-images.githubusercontent.com/5605160/42563639-66c28cba-8507-11e8-9e34-c5245b455fce.png">

**Comment by mikeeus** [comment]
This wizard looks great! How far along is it, and can I help build it out?

**Comment by paulcsmith** [comment]
Yeah I think we can close it. There might be a “revisit later” label. If not we can add one. That helps track things that can be useful later!

I’m excited to see if people find the wizard helpful. It was fun building it.

**Comment by paulcsmith** [comment]
Thank you!
