### ISSUE TITLE
Desktop notifications from CLI/Laravel should be rebranded

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_cli#249]
As someone to whom Laravel is “a php framework” it was a little unsettling to get a notification from Laravel when running `lucky run` even if it just means my assets compiled successfully. 

Desktop notifications from Lucky are a great idea, and i think it makes sense to disable the Laravel notification and render a Lucky branded one instead.

**Comment by robacarp** [comment]
For the adventurous dev wanting to do desktop notifications, I spent some time ucovering a few layers of node-packaging mess. Laravel-mix eventually uses a project called [node-notifier](https://github.com/mikaelbr/node-notifier) which vendors a pre-compiled version of [terminal-notifier.app](https://github.com/julienXX/terminal-notifier) and/or [alerter](https://github.com/vjeantet/alerter). Terminal-notifier appears to have been first built to be used with [a ruby gem of the same name](https://rubygems.org/gems/terminal-notifier).

**Comment by paulcsmith** [comment]
I found this nice little script in one of our projects that we use for notifications on Linux and OSX. I bet we could use this to easily add notifications without external dependencies!

```
#!/bin/sh
set -e


notify_mac() {
  osascript -e 'on run {theText}' -e 'display notification theText with title "My App" sound name "Glass"' -e 'end run' "$1"
}

notify_server_ready() {
  output="Server started"
  if command -v notify-send >/dev/null; then
    notify-send "$output"
  else
    if command -v osascript >/dev/null; then
      notify_mac "$output"
    fi
  fi
}


notify_server_ready
```

We could use `File.executable?` and `Process.run` to run these processes from Crystal.

**Comment by robacarp** [comment]
@paulcsmith brilliant! I love that it attempts to be cross platform with `notify-send`. I was able to get this on my mac by just pasting in the applescript:

<img alt="image" src="https://user-images.githubusercontent.com/208647/48080884-fde37680-e1ab-11e8-91a1-c06c557b4938.png">
