### ISSUE TITLE
Better usage message for lucky init

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#255]
Related to a question on gitter.

When running `lucky init -h` you get `Usage: lucky init [arguments]` which doesn't tell you where your project name goes. Running `lucky init --api test` results in an error 

```
Generating crystal project for --api
error: unknown option `api'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

Adding Lucky dependencies to shards.yml
Done generating your Lucky project

  ▸ cd into --api
  ▸ run bin/setup
  ▸ run lucky dev to start the server
```

I think there was mention of a new wizard, so this might not even be an issue soon, but just in case, I think a good fix for this would just be:

```
$ lucky init -h
Usage: lucky init PROJECT_NAME [arguments]
    --api                            Generates an api-only web app
    --no-auth                        Does not generate authentication
    -h, --help                       This help message
```

Or something along those lines.

**Comment by robacarp** [comment]
It feels backwards to me that the flags come after the app name and cannot come before. I see it the other way around frequently with terminal commands, and there are several which accept arguments in either order.

**Comment by jwoertink** [comment]
The "either order" option is probably most optimal. Gives least resistance.

I see a lot of CLI that have the options come first, but those always read like yoda speak to me lol. Like take this for example:

> make me a coffee with cream and sugar
> make coffee --with-cream --with-sugar

> make me with cream and sugar a coffee
> make --with-cream --with-sugar coffee

With that said, I'm cool with any option as long as the end result is happy, and less confused, new comers 😂

**Comment by paulcsmith** [comment]
I think ideally it should work with either option, but in the next release it will be less of an issue as the recommended way will be to use `lucky init` and use the wizard to choose what you'd like. So this isn't too of a priority in my opinion. BUT if someone wants to allow this to work with either option, that'd be great! I'd happily accept a PR

**Comment by paulcsmith** [comment]
I'm going to close this for now since the wizard is out and seems to have resolved these issues! But if someone comes across this and wants to make it work in either position I'd still accept a PR because it wouldn't hurt to improve the experience when not using the wizard
