### ISSUE TITLE
CLI help menu needs clearer error message

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#260]
I cloned latest master as of this post. Ran `crystal build --release ./src/lucky.cr` to create a fresh binary. When running `./lucky -h`, I get this error:

```
[14:49PM] lucky_cli (master)$ ./lucky -h

Missing tasks.cr file

Try this...

  ▸ Change to the directory with the tasks.cr file,
    usually your project root
  ▸ If this is a new project, run lucky init to
    create a default tasks.cr file
```

To add to this, running it from a lucky project that's already been setup (shards install, etc..) it runs fie.

**Comment by paulcsmith** [comment]
I believe this is the same with the currently released version. Lucky help shows a list of tasks you can run, but it can only run tasks if you are in a folder with `tasks.cr`

Maybe the message could be clarified? Any ideas?

**Comment by jwoertink** [comment]
Well, if you're brand new to lucky and are sitting in your Projects folder about to generate your first app, you may want to just do a quick `lucky -h` to make sure how you run the command. In this case, it would fail.

**Comment by paulcsmith** [comment]
Yeah I think the error message could definitely be improved. It should tell you you're not in a Lucky project though, but maybe make it look less like an error in `lucky -h`. Something like.

```
You are not in a Lucky project.

> Generate a new one with 'lucky init'
> Or to to your project's root directory to see what tasks are available
```

**Comment by jwoertink** [comment]
Maybe if no `tasks.cr` file is found, it's assumed you're not in a lucky folder in which case, the only help is a super basic one of how to generate a project, and the version. Then below it could say "Run this command from your lucky project folder to see more help options"

haha, you beat me to it
