### ISSUE TITLE
browser-sync inclusion for new projects should go in devDependencies

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#291]
When you generate a new project, `browser-sync` is included in the `dependencies` block, but really it should go in `devDependencies`.

For anyone that would like to tackle that, you would probably just need to update [this file](https://github.com/luckyframework/lucky_cli/blob/master/src/browser_app_skeleton/package.json).

**Comment by paulcsmith** [comment]
Done as part of 
https://github.com/luckyframework/lucky_cli/commit/88ad5af5b40f3a29c4abcb0581db505019d7003f

Thanks for the suggestion!
