### ISSUE TITLE
Switch to using https://github.com/mosop/cli

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#31]
It looks really nice and has a lot of stuff I wanted to add anyway. This will save a lot of time

https://github.com/mosop/cli

**Comment by ianagne** [comment]
This looks awesome.  Do you still want this implemented, @paulcsmith?  I'd be willing to go through the repos and make the changes to our current task system.

**Comment by paulcsmith** [comment]
I need to evaluate some other options because mosop/cli isn't being actively maintained. I'll open a new issue when we're ready to move forward!
