### ISSUE TITLE
[Feature] Allow to specify output directory for init via command line option

### ISSUE THREAD

**Issue by nicbet** [luckyframework/lucky_cli#339]
The command `lucky init [name]` creates a new new project in `./[name]`. (Same holds when executing the wizard). 

Perhaps there is a chance to expand the command line arguments the cli tool takes to be able to specify a differently named output directory, which would override `@project_dir = project_name` in the generator?

As a special corner case, I would like to be able to use the current directory as the target.

**Comment by paulcsmith** [comment]
@nicbet Thanks for opening this issue! Just to figure out how to prioritize this, could you explain how this impacts your workflow? Is this a must have or is it fairly low impact?

**Comment by nicbet** [comment]
@paulcsmith it would be more of a `nice to have`: would eliminate a copy step (see Readme https://github.com/nicbet/docker-lucky) and make the workflow more similar to other frameworks (e.g., see https://github.com/nicbet/docker-phoenix)
