### ISSUE TITLE
Extra help for tasks

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#340]
When you run `lucky -h`, you get output like:

```
Usage: lucky name.of.task [options]

Available tasks:

  ▸ build.release             Compile app for production
  ▸ db.create                 Create the database
  ▸ db.create_required_seeds  Add database records required for the app to work
  ▸ db.create_sample_seeds    Add sample database records helpful for development
  ▸ db.drop                   Drop the database
  ▸ db.migrate                Migrate the database
  ▸ db.migrate.one            Run the next pending migration
  ▸ db.redo                   Rollback then run the last migration
  ▸ db.rollback               Rollback the last migration
  ▸ db.rollback_all           Rollback all migrations
  ▸ exec                      Execute code. Use this in place of a console/REPL
  ▸ gen.action.api            Generate a new api action
  ▸ gen.action.browser        Generate a new browser action
  ▸ gen.component             Generate a new component
  ▸ gen.migration             Generate a new migration
  ▸ gen.model                 Generate a model, query, and form
  ▸ gen.page                  Generate a new page
  ▸ gen.resource.browser      Generate a resource (model, form, query, actions, and pages)
  ▸ gen.secret_key            Generate a new secret key
  ▸ routes                    Show all the routes for the app
  ▸ watch                     Start and recompile project when files change
```

For someone brand new to lucky, this is a little daunting, as well as slightly confusing.  You know that you can run a migration like `lucky gen.migration`, and you know it takes options like `[options]`, but you don't know **what** that actually looks like. _What_ `[options]` can you pass? 

For this case, it would be nice if you could do `lucky -h gen.migration` and then see output similar to:

```
Usage: lucky gen.migration AddColumnToModel

Example:

  ▸ lucky gen.migration AddNameToUsers     
```

Of course this would mean that CLI would need an optional `example` macro so your custom tasks, or tasks created by shards could be looped in.

**Comment by richarddewit** [comment]
I suggest either `lucky help gen.migration` or `lucky gen.migration --help`. Especially the `--help` one, please at least catch that, because of course I also encountered this :sweat_smile::

```
Created --help::V20190926105501 in ./db/migrations/20190926105501_--help.cr
```

**Comment by paulcsmith** [comment]
Whoops! That is actually a bug in the `--help` handler. It is supposed to have a default help message no matter what, but it doesn't work for precompiled tasks. https://github.com/luckyframework/lucky_cli/issues/417

We'll get that fixed + add some more docs to various tasks  https://github.com/luckyframework/lucky/issues/787
