### ISSUE TITLE
Add `lucky init {project} --customize`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#37]
This will walk you through setup and ask if you want certain things

* API only
* Turbolinks
* Heroku
* Brunch

etc. A walkthrough is nice because remembering flags sucks. Flags should still be available though for people that like it, and for use for other CLI tools.

**Comment by paulcsmith** [comment]
Welcome back @mikeeus! I'm glad to hear from you again :D

I'd *love* some help with this. This will be a fairly large feature I think, but it could be done in multiple PRs to keep things simple to review. I'll try to lay out roughly what needs to be done here. I think for starters a `--api` option would be good. Adding the others can come later. As always, feel free to ping me in Gitter if you need any help/advice with stuff

## Some general pointers

* The entry point for initializing a Lucky applications is: https://github.com/luckyframework/lucky_cli/blob/2064e617825b335b058ebaa8fb713035386091a0/src/lucky.cr#L45
* Which calls: https://github.com/luckyframework/lucky_cli/blob/2064e617825b335b058ebaa8fb713035386091a0/src/init_questions.cr#L6
* There is already some support for asking questions in: https://github.com/luckyframework/lucky_cli/blob/2064e617825b335b058ebaa8fb713035386091a0/src/init_questions.cr#L10-L18 but it is not documented and should be ignored for now. I'll expand it and document it later. This will be what the future `--customize` option uses.
* Generating a Lucky project is done by: https://github.com/luckyframework/lucky_cli/blob/master/src/generators/web.cr
* The templates for the `src` folder are here: https://github.com/luckyframework/lucky_cli/tree/master/src/web_app_skeleton

## With that info, here's roughly what needs to change

* https://github.com/luckyframework/lucky_cli/blob/master/src/generators/web.cr#L6-L10 should set an `@api_only` instance var to true if the user passes `--api`. You can check that directly in `ARGV` or use Crystal's [OptionParser](https://crystal-lang.org/api/0.24.2/OptionParser.html). I'm not sure which will be easiest. It's up to you :)
* Pass the `@api_only` option to the `SrcTemplate` class: `https://github.com/luckyframework/lucky_cli/blob/2064e617825b335b058ebaa8fb713035386091a0/src/generators/web.cr#L72-L74`
* Change templates in https://github.com/luckyframework/lucky_cli/tree/master/src/web_app_skeleton. You can access instance vars from the `SrcTemplate` class in templates. Such as in: https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/config/database.cr.ecr
* `app.cr` should no longer require files not relevant to APIs, e.g. src/pages, src/components
* You may need to extract a separate `BrowserSrcTemplate` class and a new `browser_app_skeleton` that only includes files that are relevant to browsers. Then only render `BrowserSrcTemplate` if `@api_only` is false. Files/folders in `browser_app_skeleton` would basically be cut from `web_app_skeleton` and moved over. Things like `src/pages`, `src/components`, `src/actions/browser_actioncr`, etc.
* A test for initializing with the `--api` option: https://github.com/luckyframework/lucky_cli/blob/master/spec/integration/init_web_spec.cr to make sure that everything compiles as expected

This is a fairly complex feature so don't hesitate to reach out again :D

**Comment by mikeeus** [comment]
This is going to be fun :D. It does seem like a large task so I'll look around and get handle of it, then create separate issues for each component and tackle them one at a time.

Thanks for the detailed write up! I'll let you know if I get stuck on anything.

**Comment by paulcsmith** [comment]
Closing in favor of https://github.com/luckyframework/lucky_cli/issues/217
