### ISSUE TITLE
Native support for task args

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#378]
Right now you can use `ARGV`, but that feels like a "loop hole" more than implementation. It'd be nice if tasks had a common interface for when you want pass args in to your task like `lucky gen.model User`.

Maybe we could have a wrapper around OptionParser? 

```crystal
class Gen::Model < LuckyCli::Task
  summary "generate a model" 
  # lucky gen.model -m User
  # lucky gen.model --model User
  # lucky gen.model User
  # lucky gen.model user  (error arg user doesn't match format...)
  param model_name, as: ["-m", "--model", ""], format: /^[A-Z].+/

  def call
    @model_name
  end
end
```

With something like this, we could add some options to it for error handling, validations, and allowing for passing in multiple args easily. 

ref: https://gitter.im/luckyframework/Lobby?at=5d4e0ca49507182477af244b

**Comment by paulcsmith** [comment]
We definitely should have this handled by lucky CLI and made easier to use. 

I did something in Up that worked well https://github.com/paulcsmith/up/blob/master/src/up/command.cr we pass the array of args to call

They are passed in here https://github.com/paulcsmith/up/blob/20710d6f5eb889994c831ed696b70fc6c8dbd80b/src/up/runner.cr#L29

I think it’d be nice to use the built in option parser if we can but add some helper methods to make it cleaner and clearer. We could experiment a bit with that. 

Maybe add some validations too so it’s easier to validate formats and such
