### ISSUE TITLE
Rails UJs update?

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#394]
I just came across this https://yarnpkg.com/en/package/@rails/ujs which shows a higher version number than https://yarnpkg.com/en/package/rails-ujs. Not sure if they are moving over, or what's up with that. Maybe we use this new one? Maybe we just roll our own LuckyUJS? No clue, but I wanted to just put this out there.

**Comment by paulcsmith** [comment]
Yeah I think we could/should use the new one. I wish they called it something else so it is clear it isn't just for Rails, but oh well :D

**Comment by jwoertink** [comment]
Well, I think that's why the update. It's under a rails namespace now, but it's just called "ujs". My guess is they are moving that direction, but wanted the name to start.

**Comment by paulcsmith** [comment]
Oh I think I get it. I've never worked with yarn/npm namespaces. So I guess you could reference the package as just Ujs? That would be super cool

**Comment by paulcsmith** [comment]
Looks like a fairly easy update: https://github.com/rails/rails/tree/master/actionview/app/assets/javascripts#installation and "Usage" under that
