### ISSUE TITLE
Check for a valid project name before asking other questions

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky_cli#405]
Currently when generating a new project you can enter whatever you want as the name, it then asks you a couple questions and then, if the name isn't valid, fails to work. It would be nice if it validated the name at the beginning.

**Comment by jwoertink** [comment]
Yup. I agree here. I've ran in to this a few times.

It looks like we already have comments and some validation on the other questions. We just need to add that to the "Project name?" one.
