### ISSUE TITLE
Error page uses normalize.css.map which throws an error

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#411]
The error page has some [normalize.css](https://github.com/luckyframework/lucky_cli/blob/master/src/browser_app_skeleton/src/pages/errors/show_page.cr#L39) embedded which has mention of a css map. That map url is wrong, so when you get an error page, there is an additional request made which fails with a 404. This is similar to how favicons work.

```
web    | GET /posts/test-blog/normalize.min.css.map
web    |  ▸ Handled by Posts::Show
web    |  ▸ Ran verify_accepted_format
web    |  ▸ Ran protect_from_forgery
web    |  ▸ Ran set_xss_guard_header
web    |  ▸ Ran set_frame_guard_header
```

We either remove the mention of the map, or add in an actual map that points to the proper spot.

**Comment by paulcsmith** [comment]
Nice catch. Let’s remove the map url

**Comment by jwoertink** [comment]
Fixed by https://github.com/luckyframework/lucky_cli/pull/454
