### ISSUE TITLE
[Webpack] Insufficient number of arguments or no entry found.

### ISSUE THREAD

**Issue by InstanceOfMichael** [luckyframework/lucky_cli#431]
`script/setup` fails on `yarn dev`

```
forge@inspiron-7573-u18:~/code/lucky-sapper/api$ yarn run webpack --progress --hide-modules --color --config=node_modules/laravel-mix/setup/webpack.config.js
yarn run v0.27.5
$ "/home/forge/code/lucky-sapper/api/node_modules/.bin/webpack"

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: a895b8d0898f714b17bf
Version: webpack 4.41.2
Time: 53ms
Built at: 10/20/2019 9:42:55 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in '/home/forge/code/lucky-sapper/api'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jwoertink** [comment]
I'll be honest... I don't know a single thing about webpack. In fact, all my lucky apps have it ripped out in favor of Gulp 😅  But let's see if we can figure this thing out. 

* Is this from a fresh lucky app?
* If not, are you able to share a package.json ?
* Can you try completely blowing out your `node_modules` directory and re-run your `yarn install`?
* Can you share your `webpack.config.js` if that doesn't work?

**Comment by InstanceOfMichael** [comment]
Its fresh. Although,  I personally want to replace it with my framework of
choice.

**Comment by jwoertink** [comment]
As long as your framework of choice generates a `public/mix-manifest.json` file, then everything else will just run seamlessly.  

I'll try generating a fresh lucky app and see if I can re-create this.

**Comment by InstanceOfMichael** [comment]
I had an old version of yarn
