### ISSUE TITLE
LuckyCli hasn't been updated to use Lucky version 0.18.1

### ISSUE THREAD

**Issue by smadeja** [luckyframework/lucky_cli#436]
Is there any reason for skipping this release?

**Comment by jwoertink** [comment]
uummm... We forgot? 😅  lol. I'll try to take a look at that here in a bit

**Comment by paulcsmith** [comment]
I'll get a new release out soon. FWIW the version was set to `~> 0.18.0` so it would use  0.18.1 of Lucky when installing, so people using Lucky CLI today should still get the latest version.

Master has some nice tweaks though so I think bumping the version and getting those out would be great!

**Comment by paulcsmith** [comment]
Closed by #437. Thanks for bringing this up!

**Comment by smadeja** [comment]
Thanks! I overlooked the little squiggly thing and was just confused as to why I couldn't install the newest version. 😅
