### ISSUE TITLE
UserSerializer doesn't inherit from BaseSerializer

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#467]
https://github.com/luckyframework/lucky_cli/blob/fa434eb898f2dd1917daf51a73df54fd0e9046e0/src/api_authentication_app_skeleton/src/serializers/user_serializer.cr#L1

I'm not sure if this is on purpose, or just missed. When you generate a new project in both full and api modes, if you select to generate auth, a `UserSerializer` will be generated for you. There's a `BaseSerializer` in that directory, but the `UserSerializer` doesn't inherit from it.

Should it? Or should it mention why it doesn't by default?

**Comment by paulcsmith** [comment]
Nice catch! Yes I think it should and I probably just forgot it when I introduced the BaseSerializer. Oops!
