### ISSUE TITLE
Move `tasks` folder into `src`?

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#474]
Kind of odd that they sit outside `src`. Original reasoning was that we didn't need to load them for the app to start, but I think that isn't a good reason. More intuitive to move them in src/tasks

**Comment by jwoertink** [comment]
I thought we had them outside of the app because they're never really used inside of the app. At least for me, these (like rake tasks) are almost their own separate app because they're run by cron jobs, or manually, or some other external process that's not the main process.

**Comment by paulcsmith** [comment]
Yeah that's a good point. Maybe it is ok as-is and I overthought it a bit :) I'll close this, but if someone else has some thoughts feel free to comment here
