### ISSUE TITLE
AppClient is always sending json Content-Type

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#492]
When we generate a project, we add this `AppClient`, but it always defaults the Content-Type to json. If you're wanting to test just normal web actions, then you always have to override this. We should just add the catch `<% if api_only? %>`, then it's a safe bet we want this. If you're doing an XML API (or whatever), then you can override this on your own 😛 

https://github.com/luckyframework/lucky_cli/blob/0b2f8bf859dd693b09e3c9ef658cdb1ac6c0c697/src/web_app_skeleton/spec/support/app_client.cr.ecr#L4

**Comment by paulcsmith** [comment]
As discussed in Gitter we'll instead create a `ApiClient` and `BrowserClient`. One for browser requests and one for Api requests. The names are symetrical with the default `Browser/ApiAction`
