### ISSUE TITLE
current_user should be memoized

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#507]
Without any changes to an app generated with authentication, a signed in page will hit the database to load the current user twice due to these calls:
- [`require_sign_in.cr:7`](https://github.com/luckyframework/lucky_cli/blob/5aabbae7e60627451cf71fe60b88c908be61802a/src/browser_authentication_app_skeleton/src/actions/mixins/auth/require_sign_in.cr#L7)
- [`main_layout.cr:41`](https://github.com/luckyframework/lucky_cli/blob/5aabbae7e60627451cf71fe60b88c908be61802a/src/browser_authentication_app_skeleton/src/pages/main_layout.cr#L41)

I believe it makes sense to generate the code with a memoized `current_user` method. This would, of course, not keep the database from being re-queried if the user was not found, but would stop querying once the user is loaded.

**Comment by matthewmcgarvey** [comment]
An example of adding memoization to `find_current_user`

```crystal
# This method tells Authentic how to find the current user
@users : Hash(String, User?)?
private def find_current_user(id) : User?
  @users ||= Hash(String, User?).new { |hash, key| hash[key] = UserQuery.new.id(key).first? }
  @users.try { |users| users[id] }
end
```

**Comment by paulcsmith** [comment]
@matthewmcgarvey This is a fantastic idea, I think this can be done using the `memoize` macro. I can make a PR for this :)

**Comment by jwoertink** [comment]
Related: https://github.com/luckyframework/authentic/issues/32

**Comment by jwoertink** [comment]
This is actually done now. We memoize this method https://github.com/luckyframework/lucky_cli/blob/5d9ddb9c19e7eb22162ec06d5687734d701f5a0f/src/browser_app_skeleton/src/actions/browser_action.cr.ecr#L43

which is called from Authentic https://github.com/luckyframework/authentic/blob/e3837d4684437ddb2e5dc04e2cc9c8f96105b2fc/src/authentic/action_helpers.cr#LL35C9-L35C26
