### ISSUE TITLE
Trim and squish envs

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky_cli#512]
Some services and such make it easy to do mistakes on LUCKY_ENV with `\n` and so on.

An idea would be to remove those to make less easy to things to break for those small things.

it could be on here: https://github.com/luckyframework/lucky_cli/blob/4ec6de7cfc00be018f328ca8b7fd509cf9118c3d/src/web_app_skeleton/config/env.cr#L11

And idea @paulcsmith wrote on gitter was this: 
```
ENV["LUCKY_ENV"]?.try(&.trim.squish) || "development"
```
But needs to be tested.

**Comment by confact** [comment]
I tested this and it worked:
ENV["LUCKY_ENV"]?.try(&.strip) || "development"

**Comment by jwoertink** [comment]
This is actually done from https://github.com/luckyframework/lucky_env
