### ISSUE TITLE
Cookie will soon be rejected because it has the "sameSite" attribute set to "none"

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky_cli#514]
I'm seeing these a lot in the browser console:

```
Cookie “_luckyapp_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies
```

Should we do something about them?

**Comment by wout** [comment]
Ok, then the `HTTP::Cookie` extension in Lucky should also be prepared for this since it doesn't have a `samesite` method.

**Comment by jwoertink** [comment]
It should have one https://github.com/crystal-lang/crystal/blob/master/src/http/cookie.cr#L22 We will just need to make sure that we can set this properly from Lucky.

**Comment by matthewmcgarvey** [comment]
If we changed it from `none` to `lax` or even `strict` does anyone know what it does? I'd really like to have a few things in this issue so that anyone can pick it up

1. resource/link on what that does
2. how will we know it works
3. what should be checked to make sure it didn't break anything
