### ISSUE TITLE
Investigate using npm out of the box over yarn

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#532]
Related: https://gitter.im/luckyframework/Lobby?at=5efe584eb8152d34847a9694
Related: https://github.com/luckyframework/lucky_cli/issues/346

I'm not great when it comes to the whole node ecosystem, but I'm under the impression that node bundles with `npm` by default, but to use yarn, you need to run an extra install step. In some cases, people using nvm to manage their node versions might install yarn through brew, and node through nvm. In the case above, he wasn't able run `./script/setup` since it failed every time running `yarn dev`. But using `npm` and `npx` both worked fine. 

Me personally, I like yarn's output, and interface better; however, it might make things easier on us to just default to npm, and then allow the user to switch to yarn. 

Does anyone have any experience where npm was default, and it didn't work, but using yarn did? 

I guess alternatively, we could add some docs saying "if this doesn't work, try using npm"...

**Comment by paulcsmith** [comment]
I think we should remove yarn. NPM is a lot better now, and removing a required dependency would be a great for the getting started experience I think

**Comment by stephendolan** [comment]
I haven't used NPM in ages, but I'd be down for this change to simplify the setup process.

**Comment by jwoertink** [comment]
The frontend ecosystem is a bit out of my wheel house... I'm doing to go with `npm`, but do we need to look in to using `npx` in our `package.json` file or is that tool only for specific cases? I know it's more implementation details, but I'd like to have everything out there so we all know the direction and such.

Also, on the topic of tossing everything out there, I think we also need to consider people that installed node / npm a long time ago and haven't updated in a while. Using older versions might break things when running a new setup. What's the best way we can determine the oldest version we could support, and how do we do a check that you have that version installed before doing anything?

**Comment by kevinsjoberg** [comment]
I've done a lot of frontend in the past year, and I haven't had any problems with npm. As @paulcsmith said, it was different story before, but today I think it's a safe bet.

I'd say, go for it! 👍

**Comment by jwoertink** [comment]
I'm moving a Lucky app over to npm to test it out. So far it looks like we can't disable the progress indicator
Ref: https://github.com/npm/cli/issues/3314

This isn't a totally huge issue if you're familiar with Lucky; however, imagine the point of someone brand new to Lucky running `./script/setup`, and then they get a massive wall of `npm WARN`

<img width="332" alt="Screen Shot 2021-08-06 at 2 52 24 PM" src="https://user-images.githubusercontent.com/2391/128574610-30e4e3d8-b416-4ddb-a8e7-b96b44b690db.png">

It looks like they have these `.npmrc` files we could generate with new apps and have some default settings, but I'm not sure which all settings we would want, and of those which work.

I'll keep an eye on that issue though.

**Comment by jwoertink** [comment]
Alright, I've spent the last 30+min trying to get one of my apps to run on npm, and I can't get it to "bundle". I'm running in to issue after issue that doesn't seem to exist when using yarn.

https://github.com/vuejs/component-compiler-utils/issues/82#issuecomment-894551358

My vote is to keep yarn as the default until after 1.0 unless someone else wants to give it a shot... 🤷‍♂️

**Comment by jwoertink** [comment]
https://freddixx.medium.com/hello-yarn-2-goodbye-node-modules-21d97afc1a75

Looks like yarn 2 may be pretty amazing.
