### ISSUE TITLE
Simplify task management architecture

### ISSUE THREAD

**Issue by jwinnie-the-great** [luckyframework/lucky_cli#539]
If I'm understanding correctly:

- `Procfile` wraps lucky_cli directly in some places, and invokes scripts inside `script/` in other places
- `script/` is a directory full of shell scripts that wrap lucky_cli
- lucky_cli wraps `tasks.cr`
- `tasks.cr` imports Lucky's default tasks as well as custom tasks in `tasks/`

For a newcomer like me this is a lot of complexity to deal with. Is there a simpler way to do things?

**Comment by jwoertink** [comment]
Pretty close. We have this guide here: https://luckyframework.org/guides/getting-started/concepts#file-structure-overview that explains what each part is for. But a quick summary:

* `Procfile` is for process management. Process managers like foreman, forego, overmind, heroku, etc... use this
* `script/` is for bash scripts your app might need.
* `tasks.cr` just loads the `tasks/` directory, but you won't ever really touch this file directly.

I know it can be quite a bit at first, but that's with any new project you start really. We can always improve the documentation to make this easier to understand, so if you have any thoughts from a fresh set of eyes, we're down to hear them!

**Comment by jwinnie** [comment]
Is it possible to replace `Procfile` with a pure-Crystal process management solution? It seems a bit odd to me to require installing a third-party process manager just to get a development environment.

**Comment by jwoertink** [comment]
There probably is, however, if you deployed your app to heroku or elastic beanstalk (or many other ones), it's common practice to use a Procfile. Whether it's a crystal app, rails, or even using [django](https://devcenter.heroku.com/articles/django-app-configuration). 

You don't have to use it though. If you want to boot your app without a process manager, you would just run the commands located in your `Procfile.dev` (mainly `lucky watch` and `yarn watch` for assets). Note that if you don't need to build assets, you can just run `crystal src/start_server.cr` and skip all the extra fluff. 

These are great questions!

**Comment by jwoertink** [comment]
I think this can be closed now. We now have a built-in Crystal solution with https://github.com/matthewmcgarvey/nox being default.
