### ISSUE TITLE
Add compress handler to default server.cr

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#54]
So it gzips HTML and JSON responses

**Comment by jwoertink** [comment]
Thinking about this one, generally whatever you have set as your proxy would handle doing this. So nginx, apache, or even the CDNs like cloudfront usually take care of this. You wouldn't want this in development.. So really we're talking if you booted the lucky app on port 80 and traffic hit it directly..

If that's the case, this is available in the crystal https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/compress_handler.cr. What are your thoughts on this?

**Comment by jwoertink** [comment]
This is technically done, right?

**Comment by paulcsmith** [comment]
Yep it is!
