### ISSUE TITLE
CLI arg format error could use love

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#556]
If you don't read Regex as a second language, then getting an error like:

> Invalid format for IndexPages. It should match /^[A-Z].+(?::+*)Page$/

can be a bit intimidating. 

One easy option could be to revamp the error in to an easy "paste" to play.crystal-lang so it looks like:

```
SomeTask was passed in invalid option format:

Be sure this condition returns true:

  "IndexPages".match?(/^[A-Z].+(?::+*)Page$/)

```

Or, another option would be to set an optional error message. Then the CLI arg becomes:

```crystal
positional_arg :page_class,
            "The name of the Page class. e.g. Users::IndexPage",
             format: /^[A-Z].+(?::+*)Page$/,
             error_message: "You did it wrong...."
```

**Comment by jwoertink** [comment]
Ok, I have an idea for this. I'm thinking instead of just raising strings, we make those raise errors. Then the user can just rescue those errors to do their own fancy errors however they need. I'm working out a PR now that I think will work.

**Comment by jwoertink** [comment]
My original idea didn't work. This will either require revamping how the exceptions are being raised currently (could get quite messy), or we could do what Habitat does and add an `example` key. The error message would then basically say either "It should match /ugly regex" or "Example: example" if the example is added...

I'll keep thinking on some other approaches, but right now that's what I'm leaning towards.

**Comment by paulcsmith** [comment]
I think an example would be great. That seems the simplest and most flexible for making sure the error output is tailored to what the user wants
