### ISSUE TITLE
Update skeleton Github Actions ci.yml to only install chromium-browser

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#564]
https://github.com/luckyframework/lucky_cli/blob/0efe5e465fb22555fa3b92c5dcb8d0eebd30fe62/src/web_app_skeleton/.github/workflows/ci.yml.ecr#L50

Right now the ci.yml file installs `chromium-chromedriver` but since generated apps have the `webdrivers.cr` shard, it can manage chromedrivers itself. A browser is needed though, so we should switch it to install `chromium-browser` and let the shard install additional dependencies where needed.

**Comment by matthewmcgarvey** [comment]
@stephendolan I figured out the webdrivers issue. The browser is still a requirement to use the drivers.

**Comment by stephendolan** [comment]
@matthewmcgarvey I can confirm that worked! https://github.com/stephendolan/lucky_jumpstart/runs/1298680502

**Comment by jwoertink** [comment]
So you either manually install the driver, or the install the browser, and the shard installs the driver?
