### ISSUE TITLE
Update generated Operations to new structure

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#574]
With https://github.com/luckyframework/avram/pull/469 being merged in, Operations now have a new interface. We need to make sure all of the generated operations are updated to use these.

**Comment by bcardiff** [comment]
I guess I've just stumbled on this one when checking avram + lucky + lucky_cli on master

```
$ lucky init.custom lucky101 --api
$ cd lucky101
$ shards
$ shards build
```

```
# Dependencies are satisfied
# Building: lucky101
# Error target lucky101 failed to compile:
# Using compiled compiler at /__w/test-ecosystem/test-ecosystem/crystal/.build/crystal
# In lib/avram/src/avram/operation.cr:81:16
# 
#  81 | abstract def run
#                    ^--
# Error: abstract `def Avram::Operation#run()` must be implemented by RequestPasswordReset
# 
```

**Comment by jwoertink** [comment]
oof 😣  sorry about that. I have #575 to fix it, but this repo is sort of a mess at the moment. Maybe I just need to merge all of these things now and fix it once everything is merged in. You're not the first this week that has run in to it. I'll try to get that fixed now.

**Comment by bcardiff** [comment]
No rush on my side. :-) the other specs passes on test-ecosystem so far https://github.com/bcardiff/test-ecosystem/runs/1359933202?check_suite_focus=true

**Comment by jwoertink** [comment]
Ok, these should be all good now @bcardiff. Hopefully they all work on your test!
