### ISSUE TITLE
Negative argument (ArgumentError): db tasks

### ISSUE THREAD

**Issue by AfroDevGirl** [luckyframework/lucky_cli#583]
Hi, I'm new to crystal and lucky and things have been well so far. But I've run into a strange issue that prevents me from running any tasks that aren't precompiled, like all of the `db.*` tasks.

### Stack Trace
```
Unhandled exception: Negative argument (ArgumentError)
  from ../../../../crystal/src/string.cr:4852:13 in '*'
  from ../../../../crystal/src/string.cr:4796:15 in 'append_error_indicator'
  from ../../../../crystal/src/compiler/crystal/exception.cr:168:9 in 'error_body'
  from ../../../../crystal/src/compiler/crystal/semantic/exception.cr:122:10 in 'append_to_s'
  from ../../../../crystal/src/compiler/crystal/semantic/exception.cr:95:7 in 'run'
  from ../../../../crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from ../../../../crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

I'm running on Fedora, lucky_cli was installed via linuxbrew and crystal is installed from source. Has anyone seen this before? Any thoughts on what could be causing it?

**Comment by matthewmcgarvey** [comment]
Hey there @AfroDevGirl 👋  Might you have a migration in your project? I recently had a migration where I used an invalid macro and got a similar error https://github.com/luckyframework/avram/issues/501

Other than that, Lucky is only verified to work with Crystal v0.35.1, if you are running Crystal built from the master branch there could be problems we don't know about.

The only other debugging step I can think of would be to try deleting your `lib/` folder and re-running `shards install` and see if that helps.

Let me know if you get somewhere with any of that

**Comment by AfroDevGirl** [comment]
I just installed from the latest release `35.1.1`, so I should be okay there. I do have a two new migrations though! In order: 
```
class EnablePostgis::V00000000000002 < Avram::Migrator::Migration::V1
    def migrate
        enable_extension "postgis"
    end

    def rollback
        disable_extension "postgis"
    end
end
``` 

```
class CreateItineraries::V20201115214805 < Avram::Migrator::Migration::V1
  def migrate
    # Learn about migrations at: https://luckyframework.org/guides/database/migrations
    create table_for(Itinerary) do
      primary_key id : Int64
      add_timestamps
      add name : String
      add start_date : Time
      add end_date : Time
    end

    execute <<-SQL
      ALTER TABLE itineraries 
      ADD COLUMN starting_location GEOGRAPHY(Point),
      ADD COLUMN ending_location GEOGRAPHY(Point)
    SQL
  end

  def rollback
    drop table_for(Itinerary)
  end
end
```

**Comment by matthewmcgarvey** [comment]
@AfroDevGirl could you try moving the execute into a second migration? I suspect the error is coming from that and then another error is happening that hides it.

**Comment by AfroDevGirl** [comment]
![headdesk](https://media.giphy.com/media/NHIecaiSc7YjK/giphy.gif) 

I feel dumb. My issue was the change I made in my user migration. `add email : String, unique: true, null: false`. Which of course should have been `add email : String, unique: true` details for that are documented [here](https://luckyframework.org/guides/database/migrations#making-columns-required-or-optional)

Apologies for my rails > crystal/lucky noob-ness!

**Comment by matthewmcgarvey** [comment]
I still think this is a real issue. We should not be hiding errors 🙈

**Comment by AfroDevGirl** [comment]
@matthewmcgarvey Yea, I wonder if a migration validator module would be beneficial if it was placed ahead of executing the db.migrate task. I'd be curious to see how rails does it, although migration errors there are also a bit mixed.

**Comment by matthewmcgarvey** [comment]
This is should be solved by https://github.com/luckyframework/avram/pull/577 and will be in the next release. Hopefully no one else has to suffer through this in the future!
