### ISSUE TITLE
consistancy with commanline flags

### ISSUE THREAD

**Issue by wontruefree** [luckyframework/lucky_cli#612]
There are a lot of designs for CLIs but I just want to link this for reference.
https://clig.dev/

I think we should rename `-v` to `--version` to be more consistent with other CLIs.

**Comment by jwoertink** [comment]
`-v` is generally the shorthand version of `--version` which I think is pretty consistent with other CLIs
<img width="236" alt="Screen Shot 2021-03-01 at 7 55 14 AM" src="https://user-images.githubusercontent.com/2391/109522781-7cdad800-7a63-11eb-8a14-7fda37b548ed.png">

I'd say the only time it's not is when `-v` stands for verbose like in `ssh`... but the LuckyCli doesn't really need a `verbose` option for anything.

**Comment by matthewmcgarvey** [comment]
I think this is the place where we handle `-v` and it seems that we do `-v` and `-version` but not `--version`

https://github.com/luckyframework/lucky_cli/blob/e405741a00c380527c8ab0a5e5e92d9881a9d937/src/lucky.cr#L39-L40

**Comment by wontruefree** [comment]
It seems like this is a little less common then I thought.  I usually associate `-v` with verbose.  This might not be something we want to do.

**Comment by jwoertink** [comment]
Agreed. For our purposes, using `v` to mean `version` is probably going to be a more common case. I'll go ahead and close this for now, but if you think of any other reasons for adding a `verbose` option, feel free to reopen it. Thanks for the suggestion!
