### ISSUE TITLE
Using shard for your own tasks includes a lot of unwanted code

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#620]
If I have a library and want to add custom tasks, I have to have a dependency on lucky_cli. Makes sense but it includes everything that is used for the CLI as well as the classes to build tasks. One of those things is the `teeplate` dependency that some of the tasks use to generate new projects ([example](https://github.com/luckyframework/lucky_cli/blob/be0369c1a30a058d35b06b091401f22aebaf8222/src/lucky_cli/api_authentication_template.cr#L2)). There's no reason to ship that dependency to user's of the library and it has downsides. On an uncached compile, a [specific macro](https://github.com/luckyframework/teeplate/blob/797fc0c5414d8eff06b6d76c04d9be881623a636/src/lib/file_tree.cr#L7-L9) in teeplate takes 10 seconds to run. So now every shard that uses lucky_cli inherits that 10 second penalty.

```bash
❯ crystal build -s --release src/lucky_cli.cr
Parse:                             00:00:00.000088009 (   0.75MB)
Semantic (top level):              00:00:09.789230517 ( 137.86MB)
Semantic (new):                    00:00:00.001426725 ( 137.86MB)
Semantic (type declarations):      00:00:00.013700447 ( 137.86MB)
Semantic (abstract def check):     00:00:00.003392430 ( 137.86MB)
Semantic (ivars initializers):     00:00:00.011461789 ( 153.86MB)
Semantic (cvars initializers):     00:00:00.231323215 ( 153.98MB)
Semantic (main):                   00:00:00.030838551 ( 153.98MB)
Semantic (cleanup):                00:00:00.003465031 ( 153.98MB)
Semantic (recursive struct check): 00:00:00.000615239 ( 153.98MB)
Codegen (crystal):                 00:00:00.266971116 ( 169.98MB)
Codegen (bc+obj):                  00:00:08.413800449 ( 169.98MB)
Codegen (linking):                 00:00:00.161235795 ( 169.98MB)
dsymutil:                          00:00:00.040868893 ( 169.98MB)

Macro runs:
 - /Users/matthew/workspace/crystal/lucky_cli/lib/teeplate/src/lib/file_tree/macros/directory.cr: 00:00:09.360855688

Codegen (bc+obj):
 - no previous .o files were reused
```

We could either break out a sub-shard that defines how tasks are created, or separate those two dependencies where `require "lucky_cli"` doesn't require the tasks files that require teeplate. That could be a separate `require "lucky_cli/tasks"`

**Comment by jwoertink** [comment]
I'd be down to make a separate `lucky_task` type shard. Maybe we could give it a better name 😂  That would make things a ton easier on having to include in breeze, avram, lucky itself... We could make the `LuckCli` literally just the app generator, and have it require the task shard.

Also, that teeplate shard is quite complicated... It does make the templating super nice, but I have no attachment to it. If you think we can roll our own version that's easier to use, then I'm cool with that. Or, we can figure out a way to remove that `run` dependency. I think it's ok to not be so "type-safe" in this case. We can bulk up on specs if we need to.
