### ISSUE TITLE
Remove installing docs from README

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_cli#680]
The README file in this repo has instructions on how to install the CLI. It's technically wrong because it has you setup the CLI from the master branch which may not always be "working". If you're using Linux, chances are, you might look here first for installing it.

Instead, we should point to the website guides so it says something like "To install the Lucky CLI, read the guides for your Operating System https://luckyframework.org/guides/getting-started/installing".

Then the remainder of the README should be explicitly for how to install the CLI for the purposes of contributing to the project itself (i.e. submitting a PR).

**Comment by Ayush0431** [comment]
hello @jwoertink is this task available ? I would like to take it up.

**Comment by jwoertink** [comment]
It sure is. It's all yours! Let me know if you have any questions about what's needed @Ayush0431 Thanks
