### ISSUE TITLE
Port of generated lucky apps (5000) conflicts with latest Mac release Control Center

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#704]
On the latest release of macOS Monterey, the Control Center app uses port 5000. I remember hearing about this, but I just spent 10 minutes trying to figure out why my lucky app would work for a bit and then I would start getting 403 Forbidden responses. This is not something we can reasonably expect developers to know about, so I think it might be best to change it to something else.

It is defined here https://github.com/luckyframework/lucky_cli/blob/6d247a4b92cfbf49364128f93cf29164d468e528/src/web_app_skeleton/config/watch.yml#L2

Might be worth noting that browsersync has it's own port of 5001, I believe, and doesn't have problems.

**Comment by jwoertink** [comment]
wow... 😐  shame on them for using that port... I haven't upgraded yet, but I can see how frustrating that would get real quick if you had no clue what to look for. Should we use 4999? 😂  

Also, I saw you linked this https://developer.apple.com/forums/thread/682332 in the discord, so I'll leave it here too.
