### ISSUE TITLE
Lucky dev isn't shown in lucky -h

### ISSUE THREAD

**Issue by colinkey** [luckyframework/lucky_cli#724]
When running `lucky -h`, it would be nice to get some information about the lucky dev command. Currently a list of available tasks is printed out. Since `lucky` is used for both tasks and running the dev process, getting information about the dev process as well as the available tasks would be helpful.

**Comment by matthewmcgarvey** [comment]
Problem line is here: https://github.com/luckyframework/lucky_cli/blob/45f35290dae282610ea6aa5012b31861c792a03e/src/lucky.cr#L28-L29

We also can't call `lucky dev -h` at the moment
