### ISSUE TITLE
Make shard.yml target generic

### ISSUE THREAD

**Issue by grepsedawk** [luckyframework/lucky_cli#735]
In shard.yml, the main target results in your app's constant name.
This means everybody's production config needs to call a different binary, which comes into play with Dockerfiles

I have a slight hack to get around this:
```bash
mv ./bin/`ls ./bin/ | head -1` /usr/local/bin/webserver
```
https://github.com/superfly/flyctl/pull/852/files#diff-338317355cac9afd0ed67e6eb8e770bd64ea5c80b801fa787af9c99511761d42R30

But it would be better if the target was just consistently named `webapp`

**Comment by jwoertink** [comment]
This one might be a little tricky. The `shard.yml` comes from `crystal init app NAME`. We either need to parse that file and do a replace, or look in to just replacing the entire `shard.yml` with our own version.

**Comment by grepsedawk** [comment]
Yeah, I agree where that gets tricky here.
I'll make a PR that we can look over on how this might look in minimalistic form, and we can go from there.

Here are a few things I'm thinking we can do here, if we did to provide this constant:

- (grep)`sed`(awk) 1 liner to mod shard.yml's `target_name:` => `webapp:` (`sed -i s/target_name:/webapp:/ shard.yml` works!)
- A _full_ parse and replace using yaml (which shouldn't be too bad to do `[:targets][0]` => delete and re-add under webapp key
- Providing the entire (potentially templated) shard.yml file from lucky side, and ignoring `crystal init`'s shard.yml all together, which you mentioned

**Comment by grepsedawk** [comment]
We could also add https://github.com/stephendolan/spark which _would_ be adding a new dependency, but it would also be a dependency of a trusted member of the crystal community; which has find&replace built in

**Comment by jwoertink** [comment]
I was thinking we might just require yaml, make a hash of the shard yaml file that we need, then write that to the file. This might make the configuration a lot easier than trying to do appending and hoping indentation is correct. Plus would allow us to manage versions and such a little easier I think.

Though, I do like the idea of adding spark. Maybe that could make the wizard easier to use... :thinking: 

/cc. @stephendolan
