### ISSUE TITLE
Embedded docs link needs url

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_cli#782]
https://github.com/luckyframework/lucky_cli/blob/d947fe68a0b29b16137101f6d5424af5933aba38/src/browser_app_skeleton/src/components/shared/layout_head.cr#L13-L16

**Comment by jwoertink** [comment]
Related: https://github.com/luckyframework/website/issues/1071

**Comment by robacarp** [comment]
On second thought I'm not convinced that the docblock even needs to be there. The rest of the helper methods in that component aren't supported by documentation. Perhaps the "only in development" should be made more explicit by doing something like:
 
```crystal
live_reload_connect_tag if Lucky::Env.development?
```

Or perhaps, alternatively, all of the method calls in that component should have a docblock that points to documentation?
