### ISSUE TITLE
Configuring server

### ISSUE THREAD

**Issue by jkthorne** [luckyframework/lucky_cli#785]
In following the 12 factor application I think any environment variable should overwrite the configuration of the application.  In development mode this is not currently happening.  This might be something that could be in core lucky and not the CLI but currently [this configuration](https://github.com/luckyframework/lucky_cli/blob/main/src/web_app_skeleton/config/server.cr.ecr#L20) was causing me some problems so I thought it might be worth changing.

**Comment by jwoertink** [comment]
Not sure why I just now got the notification for this :sweat_smile:  but did you happen to try setting the `DEV_PORT` env to see if it overrode that setting? I could have sworn ENV did take precedence already...

**Comment by jwoertink** [comment]
Fixed by https://github.com/luckyframework/lucky/pull/1788
