### ISSUE TITLE
When create a lucky app with auth, it generate migration name prefix like `00000000000001_create_users.cr`, but when generate use lucky gen.migration, use date prefix

### ISSUE THREAD

**Issue by zw963** [luckyframework/lucky_cli#797]
Following is my colver project use lucky_cli 1.0.0

```sh
db/migrations/00000000000001_create_users.cr
db/migrations/20230324050705_create_fortunes.cr
db/migrations/20230324093609_add_belongs_to_user_for_fortune.cr
```

A little wired, right? Why not both use same form?

Thanks

**Comment by jwoertink** [comment]
We do this intentionally. This is to ensure that User is created first, but also let other developers create plugins to insert migrations Like [Breeze](https://github.com/luckyframework/breeze/tree/main/db/migrations)
