### ISSUE TITLE
When create a new lucky app, the postgres_data volume never work as expected.

### ISSUE THREAD

**Issue by zw963** [luckyframework/lucky_cli#798]
When create a new lucky app, will create a docker-compose.yml like [this](https://github.com/luckyframework/lucky_cli/blob/main/src/web_app_skeleton/docker-compose.yml#L36)

```
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql
```

But above code never work,  because postgres offical Dockerfile create a new [volume](https://github.com/docker-library/postgres/blob/25b3034e9b0155c3e71acaf650243e7d12a571c1/14/bullseye/Dockerfile#L186) early from /var/lib/postgresql/data, which cause latter bind mount from /var/lib/postgresql always a empty data folder, because data folder below /var/lib/postgresql is a mounted volume.

if check docker inspect, you can see two mount point.

```json
        "Mounts": [
            {
                "Type": "volume",
                "Name": "clover_postgres_data",
                "Source": "/docker/containers/volumes/clover_postgres_data/_data",
                "Destination": "/var/lib/postgresql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "1e7cb97e7e08dbd0f38dd4855e19e7e5497afc50dcf7bd4d1819b2e06716593d",
                "Source": "/docker/containers/volumes/1e7cb97e7e08dbd0f38dd4855e19e7e5497afc50dcf7bd4d1819b2e06716593d/_data",
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

The fix is quite simple, just change ` target: /var/lib/postgresql` into ` target: /var/lib/postgresql/data`.

I give some advice in discuss [here](https://github.com/luckyframework/lucky/discussions/1791) too, but, i guess someone miss this question. :smile:

If consider accept contribute on those changes, i will create a PR for fix this.

**Comment by zw963** [comment]
BTW: to verify the volume postgres_data never work, you can try: 

1. `docker-compose up`
2. create a record.
3. `docker-compose down` to remove postgres container.
4. your's record disappear ...

**Comment by jwoertink** [comment]
Sure, you can send a PR for that fix. I think that makes sense :+1:
