### ISSUE TITLE
DB connection fail with generated config

### ISSUE THREAD

**Issue by arr-dev** [luckyframework/lucky_cli#83]
With default Postgres install, it uses peer auth, 
but setting hostname causes it to use network connection which fails by default.
Can be fixed by creating local postgres user, but it may be easier to fix in config.

Replacing hostname with `""` in this line makes it work.
https://github.com/luckyframework/cli/blob/4d558e5a852cb03915ed92c3f6230bb8aa5f8034/src/web_app_skeleton/config/database.cr.ecr#L8

Would be good if someone else can try, maybe it's only like that on my machine.
Using Ubuntu 17.04 with Postgres 9.6.

**Comment by paulcsmith** [comment]
This has now been fixed 🎉 Sorry it's been so long, but better late than never!
