### ISSUE TITLE
Add --with-page into lucky gen.action.browser task.

### ISSUE THREAD

**Issue by zw963** [luckyframework/lucky_cli#862]
For follow the discussion in following link

https://github.com/luckyframework/lucky/discussions/1794#discussioncomment-5433277

**Comment by jwoertink** [comment]
You can already do this. 

https://github.com/luckyframework/lucky/blob/e83b25ae7c35be14669ae3f63bd9c95e9cab7b1a/tasks/gen/action/browser.cr#L18

```
lucky gen.action.browser Users::Index --with-page
```

**Comment by jwoertink** [comment]
Though, I just realized that the help message doesn't tell you that :man_facepalming: I'll open an issue on that

**Comment by jwoertink** [comment]
Closing as this will be added in the next release.
